.\" dirfile_alter_entry.3.  The dirfile_alter_entry man page.
.\"
.\" (C) 2008 D. V. Wiebe
.\"
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.\" This file is part of the GetData project.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" GetData is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License along
.\" with GetData; if not, write to the Free Software Foundation, Inc.,
.\" 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
.\"
.TH dirfile_alter_entry 3 "14 December 2008" "Version 0.5.0" "GETDATA"
.SH NAME
dirfile_alter_entry \(em modify the metadata of a dirfile field
.SH SYNOPSIS
.B #include <getdata.h>
.HP
.nh
.ad l
.BI "int dirfile_alter_entry(DIRFILE *" dirfile ", const char *" field_code ,
.BI "const gd_entry_t *" entry ", int " recode );
.hy
.ad n
.SH DESCRIPTION
The
.BR dirfile_alter_entry ()
function modifies the field described by 
.I field_code
in the dirfile specified by
.I dirfile
to correspond to the new parameters specified by
.IR entry .
In addition to specifying a regular field,
.I field_code
may also refer to a metafield by specifying it using its full (slashed) field
code.

If
.I field_code
specifies a
.B RAW
field and the
.I recode
argument is non-zero, the binary file associated with the field will be
converted for changes in data type and samples-per-frame.  If
.I recode
is zero, no binary file conversion will take place.

If
.I field_code
specifies a
.B LINTERP
field and the
.I recode
argument is non-zero, the look-up table file will be moved if
.IR entry -> table
specifies a different path, overwriting an existing file with the new
pathname, if present.  If the field specified by
.I field_code
is of type other than
.B RAW
or
.BR LINTERP ,
the
.I recode
argument is ignored.

The form of
.I entry
is described in detail in the
.BR get_entry (3)
man page.  The
.IR entry -> field
and
.IR entry -> fragment_index
members are ignored by this function and need not be initialised.  All other
members appropriate to the field type of 
.I field_code
should be initialised.  To change the fragment index of a field, use
.BR dirfile_move (3).
To change the name of a field, use
.BR dirfile_rename (3).

The
.IR entry -> field_type
member must correspond to the field type of
.IR field_code .
This interface cannot be used to change the type of a given field.  To do so,
delete the old field first with
.BR dirfile_delete (3),
and then create a new field of the desired type with
.BR dirfile_add (3).

Some field parameters have special values which indicate no change should be
made to the parameter.  Specifically, if any of the string parameters are NULL,
the old value will be retained.  Similarly, if
.IR entry -> spf ", " entry -> n_fields ", or " entry -> numbits
is zero, or if
.IR entry -> bitnum
is -1, or if
.IR entry -> data_type ", or " entry -> const_type
are equal to
.BR GD_NULL , 
these parameters will not be modified.

All new values for field parameters modified by this interface must contain
numerical parameters.  Using
.B CONST
fields as parameters cannot be accomplished with this function.  To use such
.B CONST
field names, the field must be modified with
.BR dirfile_alter_spec (3)
or
.BR dirfile_malter_spec (3).

.SH RETURN VALUE
On success,
.BR dirfile_alter_entry ()
returns zero.   On error, -1 is returned and the dirfile error is set to a
non-zero error value.  Possible error values are:
.TP 8
.B GD_E_ACCMODE
The specified dirfile was opened read-only.
.TP
.B GD_E_ALLOC
The library was unable to allocate memory.
.TP
.B GD_E_BAD_CODE
The field specified by
.I field_code
was not found.
.TP
.B GD_E_BAD_DIRFILE
The supplied dirfile was invalid.
.TP
.B GD_E_BAD_ENTRY
One or more of the parameters specified in
.I entry
was invalid.
.TP
.B GD_E_BAD_FIELD_TYPE
The
.IR entry -> field_type
parameter did not correspond to the type of the field specified by
.IR field_code ,
or an attempt was made to modify the immutable
.I INDEX
field.
.TP
.B GD_E_BAD_TYPE
The
.IR entry -> data_type
parameter provided with a
.BR RAW
entry, or the
.IR entry -> const_type
parameter provided with a
.BR CONST
entry, was invalid.
.TP
.B GD_E_PROTECTED
The metadata of the fragment was protected from change.  Or, a request to
translate the binary file associated with a
.B RAW
field was attempted, but the data of the fragment was protected.
.TP
.B GD_E_RAW_IO
An I/O error occurred while translating the binary file associated with a
modified
.B RAW
field, or an I/O error occurred while attempting to rename a
.B LINTERP
table file.
.TP
.B GD_E_UNKNOWN_ENCODING
The encoding scheme of the specified format file fragment is not known to the
library.  As a result, the library was unable to translate the binary file 
be associated with a modified
.B RAW
field.
.TP
.B GD_E_UNSUPPORTED
The encoding scheme of the specified format file fragment does not support
translating the empty binary file associated with a modified
.B RAW
field.
.P
The dirfile error may be retrieved by calling
.BR get_error (3).
A descriptive error string for the last error encountered can be obtained from
a call to
.BR get_error_string (3).
.SH SEE ALSO
.BR dirfile_alter_bit (3),
.BR dirfile_alter_const (3),
.BR dirfile_alter_lincom (3),
.BR dirfile_alter_linterp (3),
.BR dirfile_alter_multiply (3),
.BR dirfile_alter_phase (3),
.BR dirfile_alter_raw (3),
.BR dirfile_alter_spec (3),
.BR dirfile_delete (3),
.BR dirfile_malter_spec (3),
.BR dirfile_metaflush (3),
.BR dirfile_move (3),
.BR dirfile_open (3),
.BR dirfile_rename (3),
.BR get_error (3),
.BR get_error_string (3),
.BR dirfile-format (5)
