.\" gd_frameoffset64.3.  The gd_frameoffset64 man page.
.\"
.\" Copyright (C) 2008, 2010 D. V. Wiebe
.\"
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.\" This file is part of the GetData project.
.\"
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.2 or
.\" any later version published by the Free Software Foundation; with no
.\" Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
.\" Texts.  A copy of the license is included in the `COPYING.DOC' file
.\" as part of this distribution.
.\"
.TH gd_frameoffset64 3 "16 July 2010" "Version 0.7.0" "GETDATA"
.SH NAME
gd_frameoffset64, gd_alter_frameoffset64 \(em report or change the frame
offset of fields in a dirfile, with largefile support
.SH SYNOPSIS
.B #define _LARGEFILE64_SOURCE

.B #include <getdata.h>
.HP
.nh
.ad l
.BI "off64_t gd_frameoffset(DIRFILE *" dirfile ", int " fragment_index );
.HP
.BI "int gd_alter_frameoffset64(DIRFILE *" dirfile ", off64_t " offset ,
.BI "int " fragment_index ", int " move );
.hy
.ad n
.SH DESCRIPTION
These version of
.BR gd_frameoffset (3)
and
.BR gd_alter_frameoffset (3)
use a 64-bit offset type, even if
.I off_t
is a 32-bit type.  They are only available if the caller defines
.I _LARGEFILE64_SOURCE 
before including getdata.h.

If
.I off_t
is a 64-bit type (i.e. if
.I _FILE_OFFSET_BITS
is defined to be 64), these function will be called
.BR gd_frameoffset ()
and
.BR gd_alter_frameoffset ().
Otherwise,
.BR gd_frameoffset ()
and
.BR gd_alter_frameoffset ()
will be versions of these functions which use a 32-bit
.IR off_t .
.SH SEE ALSO
.BR gd_alter_frameoffset (3),
.BR gd_frameoffset (3),
.BR feature_test_macros (7)
