.\" gd_reference.3.  The gd_reference man page.
.\"
.\" Copyright (C) 2008, 2010 D. V. Wiebe
.\"
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.\" This file is part of the GetData project.
.\"
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.2 or
.\" any later version published by the Free Software Foundation; with no
.\" Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
.\" Texts.  A copy of the license is included in the `COPYING.DOC' file
.\" as part of this distribution.
.\"
.TH gd_reference 3 "20 July 2010" "Version 0.7.0" "GETDATA"
.SH NAME
gd_reference \(em retrieve or set the reference field for a dirfile
.SH SYNOPSIS
.B #include <getdata.h>
.HP
.nh
.ad l
.BI "const char *gd_reference(DIRFILE *" dirfile ", const char"
.BI * field_code );
.hy
.ad n
.SH DESCRIPTION
The
.BR gd_reference ()
function sets or retrieves the reference field (see 
.BR dirfile (5))
associated with the dirfile specified by
.IR dirfile .
If the
.I field_code
argument is non-NULL, the reference field for the dirfile will be set to the
field specified.  If
.I field_code
is NULL, the reference field is not modified.  The field code should refer to
a RAW field, and may not contain a representation suffix.

.SH RETURN VALUE
On success,
.BR gd_reference ()
returns the field code of the dirfile's reference field, which will be
.IR field_code ,
if
.I field_code
is non-NULL.   If no
.B RAW
fields are defined in the dirfile, this function will return NULL, without
raising an error.  On error, NULL is returned and the dirfile error is set to a
non-zero error value.  Possible error values are:
.TP 8
.B GD_E_ACCMODE
The specified dirfile was opened read-only.
.TP
.B GD_E_ALLOC
The library was unable to allocate memory.
.TP
.B GD_E_BAD_CODE
The field specified by
.I field_code
was not found.
.TP
.B GD_E_BAD_DIRFILE
The supplied dirfile was invalid.
.TP
.B GD_E_BAD_FIELD_TYPE
The field specified by
.I field_code
was not a
.B RAW
field.
.TP
.B GD_E_PROTECTED
The metadata of the primary format specification fragment (the file named
.I format
in the root dirfile directory) was protected from change.
.P
The dirfile error may be retrieved by calling
.BR gd_error (3).
A descriptive error string for the last error encountered can be obtained from
a call to
.BR gd_error_string (3).
.SH SEE ALSO
.BR gd_metaflush (3),
.BR gd_open (3),
.BR gd_error (3),
.BR gd_error_string (3),
.BR dirfile (5),
.BR dirfile-format (5)
