.\" get_frameoffset64.3.  The get_frameoffset64 man page.
.\"
.\" (C) 2008 D. V. Wiebe
.\"
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.\" This file is part of the GetData project.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" GetData is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License along
.\" with GetData; if not, write to the Free Software Foundation, Inc.,
.\" 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
.\"
.TH get_frameoffset64 3 "8 December 2008" "Version 0.5.0" "GETDATA"
.SH NAME
get_frameoffset64 dirfile_alter_frameoffset64 \(em report or change the frame
offset of fields in a dirfile, with largefile support
.SH SYNOPSIS
.B #define _LARGEFILE64_SOURCE

.B #include <getdata.h>
.HP
.nh
.ad l
.BI "off64_t get_frameoffset(DIRFILE *" dirfile ", int " fragment_index );
.HP
.BI "int dirfile_alter_frameoffset64(DIRFILE *" dirfile ", off64_t " offset ,
.BI "int " fragment_index ", int " move );
.hy
.ad n
.SH DESCRIPTION
These version of
.BR get_frameoffset (3)
and
.BR dirfile_alter_frameoffset (3)
use a 64-bit offset type, even if
.I off_t
is a 32-bit type.  They are only available if the caller defines
.I _LARGEFILE64_SOURCE 
before including getdata.h.

If
.I off_t
is a 64-bit type (i.e. if
.I _FILE_OFFSET_BITS
is defined to be 64), these function will be called
.BR get_frameoffset ()
and
.BR dirfile_alter_frameoffset ().
Otherwise,
.BR get_frameoffset ()
and
.BR dirfile_alter_frameoffset ()
will be versions of these functions which use a 32-bit
.IR off_t .
.SH SEE ALSO
.BR dirfile_alter_frameoffset (3),
.BR get_frameoffset (3),
.BR feature_test_macros (7)
