.\" get_nmfields.3.  The get_nmfields man page.
.\"
.\" (C) 2008 D. V. Wiebe
.\"
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.\" This file is part of the GetData project.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" GetData is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License along
.\" with GetData; if not, write to the Free Software Foundation, Inc.,
.\" 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
.\"
.TH get_nmfields 3 "8 December 2008" "Version 0.5.0" "GETDATA"
.SH NAME
get_nmfields \(em report the number of metafields in a dirfile
.SH SYNOPSIS
.B #include <getdata.h>
.HP
.nh
.ad l
.BI "unsigned int get_nmfields(DIRFILE *" dirfile ", const char *" parent );
.hy
.ad n
.SH DESCRIPTION
The
.BR get_nmfields ()
function queries a dirfile(5) database specified by
.I dirfile
and returns the number of metafields defined in the database for the parent
field specified by
.IR parent .

The 
.I dirfile
argument must point to a valid DIRFILE object previously created by a call to
.BR dirfile_open (3).

.SH RETURN VALUE
Upon successful completion,
.BR get_nmfields ()
returns the number of defined metafields for the given parent.  On error, it
returns zero and sets the dirfile error
to a non-zero error value.  Possible error values are:
.TP 8
.B GD_E_BAD_CODE
The supplied parent field code was not found, or referred to a metafield itself.
.TP
.B GD_E_BAD_DIRFILE
The supplied dirfile was invalid.
.P
The dirfile error may be retrieved by calling
.BR get_error (3).
A descriptive error string for the last error encountered can be obtained from
a call to
.BR get_error_string (3).
.SH SEE ALSO
.BR dirfile (5),
.BR dirfile_open (3),
.BR get_error (3),
.BR get_error_string (3),
.BR get_mfield_list (3),
.BR get_nfields (3),
.BR get_nmfields_by_type (3),
.BR get_nmvectors (3)
