name: Wheels

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # macos-15-intel for x86_64 (min macOS 15.0), macos-14 for ARM (min macOS 14.0)
          - os: macos-15-intel
            python: '3.12'
            build: 'cp*-macosx_x86_64'
            target: '15.0'
            prefix: /usr/local

          - os: macos-14
            python: '3.12'
            build: 'cp*-macosx_arm64'
            target: '14.0'
            prefix: /opt/homebrew

          - os: ubuntu-latest
            python: '3.12'
            build: 'cp*-manylinux_x86_64'
            prefix: /usr

          - os: windows-latest
            python: '3.12'
            build: 'cp*-win_amd64'
            prefix: 'C:\Program Files'

    steps:
      - name: Setup environment
        run: echo "PREFIX=${{ matrix.prefix }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      # Used to host cibuildwheel
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Setup macOS environment
        if: runner.os == 'macOS'
        run: |
          echo "MACOSX_DEPLOYMENT_TARGET=${{ matrix.target }}" >> $GITHUB_ENV

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.3.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse bindings/python
        env:
          CIBW_BUILD: ${{ matrix.build }}
          CIBW_SKIP: cp38*
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y cmake bzip2-devel flac-devel xz-devel pcre-devel zziplib-devel libzstd-devel
          CIBW_BEFORE_ALL_MACOS: >
            brew install --quiet cmake bzip2 flac xz pcre libzzip zstd
          CIBW_BEFORE_ALL_WINDOWS: >
            vcpkg install bzip2 zlib liblzma libflac zziplib pcre zstd --triplet x64-windows-static-md &&
            choco install pkgconfiglite -y --no-progress
          CIBW_ENVIRONMENT_MACOS: >
            PKG_CONFIG_PATH=${{ matrix.prefix }}/lib/pkgconfig
            PREFIX=${{ matrix.prefix }}
          CIBW_ENVIRONMENT_WINDOWS: >
            PKG_CONFIG_PATH="$VCPKG_INSTALLATION_ROOT/installed/x64-windows-static-md/lib/pkgconfig"
            CMAKE_PREFIX_PATH="$VCPKG_INSTALLATION_ROOT/installed/x64-windows-static-md"
            CMAKE_ARGS="-DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static-md"
            SKBUILD_BUILD_DIR="build/{wheel_tag}"
            MSBUILDDISABLENODEREUSE=1
          CIBW_BEFORE_BUILD: >
            python -m pip install "scikit-build-core>=0.5" "numpy>=2.0"
          CIBW_BEFORE_BUILD_WINDOWS: >
            pip install delvewheel "scikit-build-core>=0.5" "numpy>=2.0"
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: >
            delvewheel repair --add-path %VCPKG_INSTALLATION_ROOT%\installed\x64-windows-static-md\bin -vv -w {dest_dir} {wheel}
          CIBW_BUILD_VERBOSITY: 1
          CIBW_TEST_COMMAND_LINUX: >
            python {project}/bindings/python/test/test_wheel.py
          CIBW_TEST_COMMAND_MACOS: >
            python {project}/bindings/python/test/test_wheel.py
          CIBW_TEST_COMMAND_WINDOWS: >
            python {project}\bindings\python\test\test_wheel.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheel-${{ matrix.os }}
          path: ./wheelhouse/pygetdata*.whl

  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
